version: '3'

services:

  mimic-api:
    image: zhikiri/mimic:2.3.4
    container_name: mimic
    volumes:
      - ./mocks:/mimic/mocks
    environment:
      - API_PORT=8080
      - MOCKS_PATH=/mimic/mocks
    ports:
      - 8080:8080

  mimic-ui:
    image: node:11.10
    container_name: mimic-ui
    command: "./node_modules/.bin/ng serve --proxy-config proxy.conf.json --host=0.0.0.0 --disableHostCheck=true"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:4200
    depends_on:
      - mimic-api

  mimic-static-ui:
    build: ./
    container_name: mimic-static-ui
    ports:
      - 8888:80
    depends_on:
      - mimic-api
